// Generated by Haxe 4.1.1
(function ($hx_exports, $global) { "use strict";
$hx_exports["gms"] = $hx_exports["gms"] || {};
$hx_exports["gms"]["module"] = $hx_exports["gms"]["module"] || {};
$hx_exports["gms"]["module"]["analytics"] = $hx_exports["gms"]["module"]["analytics"] || {};
var $estr = function() { return js_Boot.__string_rec(this,''); },$hxEnums = $hxEnums || {},$_;
function $extend(from, fields) {
	var proto = Object.create(from);
	for (var name in fields) proto[name] = fields[name];
	if( fields.toString !== Object.prototype.toString ) proto.toString = fields.toString;
	return proto;
}
var HxOverrides = function() { };
HxOverrides.__name__ = true;
HxOverrides.remove = function(a,obj) {
	var i = a.indexOf(obj);
	if(i == -1) {
		return false;
	}
	a.splice(i,1);
	return true;
};
HxOverrides.now = function() {
	return Date.now();
};
Math.__name__ = true;
var Reflect = function() { };
Reflect.__name__ = true;
Reflect.field = function(o,field) {
	try {
		return o[field];
	} catch( _g ) {
		return null;
	}
};
Reflect.fields = function(o) {
	var a = [];
	if(o != null) {
		var hasOwnProperty = Object.prototype.hasOwnProperty;
		for( var f in o ) {
		if(f != "__id__" && f != "hx__closures__" && hasOwnProperty.call(o,f)) {
			a.push(f);
		}
		}
	}
	return a;
};
var Std = function() { };
Std.__name__ = true;
Std.string = function(s) {
	return js_Boot.__string_rec(s,"");
};
Std.parseInt = function(x) {
	if(x != null) {
		var _g = 0;
		var _g1 = x.length;
		while(_g < _g1) {
			var i = _g++;
			var c = x.charCodeAt(i);
			if(c <= 8 || c >= 14 && c != 32 && c != 45) {
				var nc = x.charCodeAt(i + 1);
				var v = parseInt(x,nc == 120 || nc == 88 ? 16 : 10);
				if(isNaN(v)) {
					return null;
				} else {
					return v;
				}
			}
		}
	}
	return null;
};
var gms_EventBusClient = function(T) {
	this.Connected = false;
	this.Connected = false;
	this.RegisteredAddresses = [];
	this.transport = T;
	this.transport.MessageReceived().Add($bind(this,this.OnMessageReceived));
	this.transport.SocketStatus().Add($bind(this,this.OnSocketStatusChanged));
	T.SetPath("/eventbus/websocket");
	T.Connect();
	this.SIG_Message = new gms_Signal();
	this.SIG_MessageError = new gms_Signal3();
	this.SIG_EventBusStatus = new gms_Signal();
	this.ExternalLog = null;
};
gms_EventBusClient.__name__ = true;
gms_EventBusClient.Create = function(ip,port) {
	var T = new gms_net_TransporterWebSocket();
	T.EndpointAddress(ip,port);
	return new gms_EventBusClient(T);
};
gms_EventBusClient.IsValid = function(s) {
	if(s != null) {
		return s.length > 0;
	} else {
		return false;
	}
};
gms_EventBusClient.prototype = {
	MessageSignal: function() {
		return this.SIG_Message;
	}
	,MessageErrorSignal: function() {
		return this.SIG_MessageError;
	}
	,log: function(txt) {
		if(this.ExternalLog != null) {
			this.ExternalLog(txt);
		}
	}
	,IsConnected: function() {
		return this.Connected;
	}
	,EventBusStatus: function() {
		return this.SIG_EventBusStatus;
	}
	,send: function(address,replyAddress,headers,body) {
		if(!this.Connected || !gms_EventBusClient.IsValid(address) || body == null) {
			return false;
		}
		var message = gms_EventBusMessage.Create("send",address,replyAddress,headers,body);
		var msg = gms_tool_Json.stringify(message);
		this.transport.SendText(msg);
		return true;
	}
	,publish: function(address,headers,body) {
		if(!this.Connected || !gms_EventBusClient.IsValid(address) || body == null) {
			return false;
		}
		var message = gms_EventBusMessage.Create("publish",address,null,headers,body);
		var msg = gms_tool_Json.stringify(message);
		this.transport.SendText(msg);
		return true;
	}
	,register: function(address,headers) {
		if(!gms_EventBusClient.IsValid(address)) {
			return;
		}
		if(gms_system_Cs2Hx.FindIndex(this.RegisteredAddresses,function(x) {
			return gms_system_Cs2Hx.Equals_String(x.address,address);
		}) < 0) {
			this.RegisteredAddresses.push(new gms_EventBusClient_$EventBusAddress(address,headers));
		}
		this.register_internal(address,headers);
	}
	,register_internal: function(address,headers) {
		if(!this.Connected || !gms_EventBusClient.IsValid(address)) {
			return;
		}
		this.log("$$$$$$$$$");
		this.log("register : " + address);
		this.log("$$$$$$$$$");
		var message = gms_EventBusMessage.Create("register",address,null,headers,null);
		var msg = gms_tool_Json.stringify(message);
		this.transport.SendText(msg);
	}
	,unregister: function(address) {
		if(!gms_EventBusClient.IsValid(address)) {
			return;
		}
		var id = gms_system_Cs2Hx.FindIndex(this.RegisteredAddresses,function(x) {
			return gms_system_Cs2Hx.Equals_String(x.address,address);
		});
		if(id >= 0) {
			this.RegisteredAddresses.splice(id,1);
		}
		this.unregister_internal(address);
	}
	,unregister_internal: function(address) {
		if(!this.Connected || !gms_EventBusClient.IsValid(address)) {
			return;
		}
		this.log("$$$$$$$$$");
		this.log("unregister : " + address);
		this.log("$$$$$$$$$");
		var message = gms_EventBusMessage.Create("unregister",address,null,null,null);
		var msg = gms_tool_Json.stringify(message);
		this.transport.SendText(msg);
	}
	,ping: function() {
		var message = gms_EventBusMessage.Create("ping",null,null,null,null);
		var msg = gms_tool_Json.stringify(message);
		this.transport.SendText(msg);
	}
	,OnMessageReceived: function(msg) {
		if(!gms_EventBusClient.IsValid(msg)) {
			return;
		}
		this.log("$$$$$$$$$");
		this.log(msg);
		this.log("$$$$$$$$$");
		var M = gms_tool_Json.parse(msg,gms_EventBusMessage);
		if(M == null) {
			return;
		}
		if(gms_system_Cs2Hx.Equals_String(M.type,"rec")) {
			this.message(M);
		} else if(gms_system_Cs2Hx.Equals_String(M.type,"message")) {
			this.message(M);
		} else if(gms_system_Cs2Hx.Equals_String(M.type,"err")) {
			this.err(M);
		} else if(gms_system_Cs2Hx.Equals_String(M.type,"pong")) {
			this.pong();
		}
	}
	,message: function(M) {
		if(gms_EventBusClient.IsValid(M.address)) {
			this.SIG_Message.Send(M);
		} else {
			this.log("$$$$$$$$$");
			this.log("EventBus Failure : address : " + M.address + ", failureCode : " + M.failureCode + ", failureType : " + M.failureType + ", message : " + M.message);
			this.log("$$$$$$$$$");
			this.SIG_MessageError.Send(M.failureCode,M.failureType,M.message);
		}
	}
	,err: function(M) {
		this.log("$$$$$$$$$");
		this.log("EventBus 'err', address : " + M.address + ", message : " + M.message);
		this.log("$$$$$$$$$");
		this.SIG_MessageError.Send(-1,"err",M.message);
	}
	,pong: function() {
		this.log("$$$$$$$$$");
		this.log("pong");
		this.log("$$$$$$$$$");
	}
	,OnSocketStatusChanged: function(status,msg) {
		this.log("$$$$$$$$$");
		this.log("OnSocketStatusChanged : " + (status == null ? "null" : "" + status) + (msg != null ? ", " + msg : ""));
		this.log("$$$$$$$$$");
		this.Connected = status;
		if(status) {
			var _g = 0;
			var _g1 = this.RegisteredAddresses;
			while(_g < _g1.length) {
				var A = _g1[_g];
				++_g;
				this.register_internal(A.address,A.headers);
			}
		}
		this.SIG_EventBusStatus.Send(status);
	}
	,__class__: gms_EventBusClient
};
var gms_EventBusClient_$EventBusAddress = function(addr,hds) {
	this.address = addr;
	this.headers = hds;
};
gms_EventBusClient_$EventBusAddress.__name__ = true;
gms_EventBusClient_$EventBusAddress.prototype = {
	__class__: gms_EventBusClient_$EventBusAddress
};
var gms_EventBusMessage = function() {
	this.failureCode = 0;
};
gms_EventBusMessage.__name__ = true;
gms_EventBusMessage.Create = function(Type1,Address,ReplyAddress,Headers1,Body) {
	if(Type1 == null) {
		return null;
	}
	var msg = new gms_EventBusMessage();
	msg.type = Type1;
	msg.address = Address;
	msg.replyAddress = ReplyAddress;
	msg.headers = Headers1;
	msg.body = Body;
	return msg;
};
gms_EventBusMessage.prototype = {
	__class__: gms_EventBusMessage
};
var gms_Signal = function() {
	this.RemoveList = [];
	this.ActionList = [];
};
gms_Signal.__name__ = true;
gms_Signal.prototype = {
	Send: function(t) {
		var a = this.RemoveList;
		a.splice(0,a.length);
		var i = 0;
		while(i < this.ActionList.length) {
			var A = this.ActionList[i];
			if(!A.execute(t)) {
				this.RemoveList.push(i);
			}
			++i;
		}
		var i = 0;
		while(i < this.RemoveList.length) {
			this.ActionList.splice(this.RemoveList[i] - i,1);
			++i;
		}
	}
	,GetID: function(cb) {
		return gms_system_Cs2Hx.FindIndex(this.ActionList,function(x) {
			return x.Action == cb;
		});
	}
	,Exist: function(cb) {
		return this.GetID(cb) >= 0;
	}
	,Add: function(cb) {
		if(!this.Exist(cb)) {
			this.ActionList.push(new gms_Signal_$SignalAction(cb,-1));
		}
	}
	,AddAndExecuteOnce: function(cb) {
		if(!this.Exist(cb)) {
			this.ActionList.push(new gms_Signal_$SignalAction(cb,1));
		}
	}
	,AddAndSetExecutionNB: function(cb,nb) {
		if(!this.Exist(cb)) {
			this.ActionList.push(new gms_Signal_$SignalAction(cb,nb));
		}
	}
	,Remove: function(cb) {
		var id = this.GetID(cb);
		if(id >= 0) {
			this.ActionList.splice(id,1);
		}
	}
	,__class__: gms_Signal
};
var gms_Signal2 = function() {
	this.RemoveList = [];
	this.ActionList = [];
};
gms_Signal2.__name__ = true;
gms_Signal2.prototype = {
	Send: function(t,u) {
		var a = this.RemoveList;
		a.splice(0,a.length);
		var i = 0;
		while(i < this.ActionList.length) {
			var A = this.ActionList[i];
			if(!A.execute(t,u)) {
				this.RemoveList.push(i);
			}
			++i;
		}
		var i = 0;
		while(i < this.RemoveList.length) {
			this.ActionList.splice(this.RemoveList[i] - i,1);
			++i;
		}
	}
	,GetID: function(cb) {
		return gms_system_Cs2Hx.FindIndex(this.ActionList,function(x) {
			return x.Action == cb;
		});
	}
	,Exist: function(cb) {
		return this.GetID(cb) >= 0;
	}
	,Add: function(cb) {
		if(!this.Exist(cb)) {
			this.ActionList.push(new gms_Signal2_$SignalAction(cb,-1));
		}
	}
	,AddAndExecuteOnce: function(cb) {
		if(!this.Exist(cb)) {
			this.ActionList.push(new gms_Signal2_$SignalAction(cb,1));
		}
	}
	,AddAndSetExecutionNB: function(cb,nb) {
		if(!this.Exist(cb)) {
			this.ActionList.push(new gms_Signal2_$SignalAction(cb,nb));
		}
	}
	,Remove: function(cb) {
		var id = this.GetID(cb);
		if(id >= 0) {
			this.ActionList.splice(id,1);
		}
	}
	,__class__: gms_Signal2
};
var gms_Signal2_$SignalAction = function(action,exec_nb) {
	this.ExecutionNumber = 0;
	this.Action = action;
	this.ExecutionNumber = exec_nb;
};
gms_Signal2_$SignalAction.__name__ = true;
gms_Signal2_$SignalAction.prototype = {
	execute: function(t,u) {
		if(this.ExecutionNumber == 0) {
			return false;
		}
		if(this.ExecutionNumber > 0) {
			this.ExecutionNumber--;
		}
		this.Action(t,u);
		return true;
	}
	,__class__: gms_Signal2_$SignalAction
};
var gms_Signal3 = function() {
	this.RemoveList = [];
	this.ActionList = [];
};
gms_Signal3.__name__ = true;
gms_Signal3.prototype = {
	Send: function(t,u,v) {
		var a = this.RemoveList;
		a.splice(0,a.length);
		var i = 0;
		while(i < this.ActionList.length) {
			var A = this.ActionList[i];
			if(!A.execute(t,u,v)) {
				this.RemoveList.push(i);
			}
			++i;
		}
		var i = 0;
		while(i < this.RemoveList.length) {
			this.ActionList.splice(this.RemoveList[i] - i,1);
			++i;
		}
	}
	,GetID: function(cb) {
		return gms_system_Cs2Hx.FindIndex(this.ActionList,function(x) {
			return x.Action == cb;
		});
	}
	,Exist: function(cb) {
		return this.GetID(cb) >= 0;
	}
	,Add: function(cb) {
		if(!this.Exist(cb)) {
			this.ActionList.push(new gms_Signal3_$SignalAction(cb,-1));
		}
	}
	,AddAndExecuteOnce: function(cb) {
		if(!this.Exist(cb)) {
			this.ActionList.push(new gms_Signal3_$SignalAction(cb,1));
		}
	}
	,AddAndSetExecutionNB: function(cb,nb) {
		if(!this.Exist(cb)) {
			this.ActionList.push(new gms_Signal3_$SignalAction(cb,nb));
		}
	}
	,Remove: function(cb) {
		var id = this.GetID(cb);
		if(id >= 0) {
			this.ActionList.splice(id,1);
		}
	}
	,__class__: gms_Signal3
};
var gms_Signal3_$SignalAction = function(action,exec_nb) {
	this.ExecutionNumber = 0;
	this.Action = action;
	this.ExecutionNumber = exec_nb;
};
gms_Signal3_$SignalAction.__name__ = true;
gms_Signal3_$SignalAction.prototype = {
	execute: function(t,u,v) {
		if(this.ExecutionNumber == 0) {
			return false;
		}
		if(this.ExecutionNumber > 0) {
			this.ExecutionNumber--;
		}
		this.Action(t,u,v);
		return true;
	}
	,__class__: gms_Signal3_$SignalAction
};
var gms_Signal_$SignalAction = function(action,exec_nb) {
	this.ExecutionNumber = 0;
	this.Action = action;
	this.ExecutionNumber = exec_nb;
};
gms_Signal_$SignalAction.__name__ = true;
gms_Signal_$SignalAction.prototype = {
	execute: function(t) {
		if(this.ExecutionNumber == 0) {
			return false;
		}
		if(this.ExecutionNumber > 0) {
			this.ExecutionNumber--;
		}
		this.Action(t);
		return true;
	}
	,__class__: gms_Signal_$SignalAction
};
var gms_UpdateManager = function() {
};
gms_UpdateManager.__name__ = true;
gms_UpdateManager.cctor = function() {
	gms_UpdateManager.PrevTime = gms_tool_Timer.stamp();
	gms_UpdateManager.MinimalTimeStep = 0.2;
	gms_UpdateManager.UpdateCallbacks = [];
};
gms_UpdateManager.Add = function(update_cb,priority) {
	if(gms_system_Cs2Hx.FindIndex(gms_UpdateManager.UpdateCallbacks,function(x) {
		return x.CB == update_cb;
	}) < 0) {
		gms_UpdateManager.UpdateCallbacks.push(new gms_UpdateManager_$UpdateEntity(update_cb,priority));
	}
	gms_UpdateManager.UpdateCallbacks.sort(function(x,y) {
		if(x.Priority < y.Priority) {
			return -1;
		} else if(x.Priority > y.Priority) {
			return 1;
		} else {
			return 0;
		}
	});
};
gms_UpdateManager.Remove = function(update_cb) {
	var id = gms_system_Cs2Hx.FindIndex(gms_UpdateManager.UpdateCallbacks,function(x) {
		return x.CB == update_cb;
	});
	if(id >= 0) {
		gms_UpdateManager.UpdateCallbacks.splice(id,1);
	}
};
gms_UpdateManager.Update = function() {
	var t = gms_tool_Timer.stamp();
	var dt = t - gms_UpdateManager.PrevTime;
	if(dt < gms_UpdateManager.MinimalTimeStep) {
		return;
	}
	gms_UpdateManager.PrevTime = t;
	var RemoveList = null;
	var i = 0;
	while(i < gms_UpdateManager.UpdateCallbacks.length) {
		var u = gms_UpdateManager.UpdateCallbacks[i];
		if(u.CB == null) {
			if(RemoveList == null) {
				RemoveList = [];
			}
			RemoveList.push(i);
		} else {
			u.CB(t,dt);
		}
		++i;
	}
	if(RemoveList != null) {
		var i = 0;
		while(i < RemoveList.length) {
			gms_UpdateManager.UpdateCallbacks.splice(RemoveList[i] - i,1);
			++i;
		}
	}
};
gms_UpdateManager.prototype = {
	__class__: gms_UpdateManager
};
var gms_UpdateManager_$UpdateEntity = function(cb,priority) {
	this.Priority = 0;
	this.CB = cb;
	this.Priority = priority;
};
gms_UpdateManager_$UpdateEntity.__name__ = true;
gms_UpdateManager_$UpdateEntity.prototype = {
	__class__: gms_UpdateManager_$UpdateEntity
};
var gms_VertxCmd = function() {
	this.SendCounter = 0;
	this.PendingMessages = [];
	this.Time_NextPingSession = 0;
	this.PingSessionTimer = 300;
	this.Time_NextPing = 0;
	this.PingTimer = 0;
	this.SIG_MeetingMessage = new gms_Signal3();
	this.SIG_SessionStatus = new gms_Signal();
	this.SIG_SocketConnection = new gms_Signal2();
};
gms_VertxCmd.__name__ = true;
gms_VertxCmd.Create = function(ip,port) {
	var vcmd = new gms_VertxCmd();
	vcmd.CommonInit(ip,port);
	return vcmd;
};
gms_VertxCmd.ToInt = function(s,default_value) {
	if(gms_VertxCmd.IsValid(s)) {
		return Std.parseInt(s);
	} else {
		return default_value;
	}
};
gms_VertxCmd.IsValid = function(s) {
	if(s != null) {
		return s.length > 0;
	} else {
		return false;
	}
};
gms_VertxCmd.prototype = {
	CommonInit: function(ip,port) {
		this.Net = new gms_net_TransporterWebSocket();
		this.Net.EndpointAddress(ip,port);
		this.Net.MessageReceived().Add($bind(this,this.OnMessageReceived));
		this.Net.SocketStatus().Add($bind(this,this.OnSocketStatusChanged));
		gms_UpdateManager.Add($bind(this,this.UpdateCB),0);
	}
	,EventBusRegisterOnce: function(status) {
		if(status) {
			this.EventBus.register("time",null);
			this.EventBus.EventBusStatus().Remove($bind(this,this.EventBusRegisterOnce));
		}
	}
	,getSessionToken: function() {
		return this._SessionToken;
	}
	,setSessionToken: function(value) {
		this.SIG_SessionStatus.Send((this._SessionToken = value) != null);
		this.Log("===========================");
		this.Log("Session validity : " + Std.string(this.IsSessionValid()));
		this.Log("===========================");
	}
	,getNetTransporter: function() {
		return this.Net;
	}
	,GetUserLogin: function() {
		return this.UserLogin;
	}
	,GetUserPseudo: function() {
		return this.UserPseudo;
	}
	,IsSessionValid: function() {
		return gms_VertxCmd.IsValid(this.getSessionToken());
	}
	,IsSessionValidAndConnected: function() {
		if(this.IsSessionValid()) {
			return this.Net.IsConnected();
		} else {
			return false;
		}
	}
	,IsSessionValidOrInProgress: function() {
		if(!this.IsSessionValid()) {
			return gms_system_Cs2Hx.FindIndex(this.PendingMessages,function(x) {
				return gms_system_Cs2Hx.Equals_String(x.Msg.Name,"UserConnect");
			}) >= 0;
		} else {
			return true;
		}
	}
	,SetExternalLog: function(elog) {
		this.ExternalLog = elog;
		if(this.EventBus != null) {
			this.EventBus.ExternalLog = elog;
		}
		if(this.Net != null) {
			this.Net.ExternalLog = elog;
		}
	}
	,Log: function(txt) {
		if(this.ExternalLog != null) {
			this.ExternalLog(txt);
		}
	}
	,Assert: function(v) {
	}
	,Ping: function(user_cb) {
		return this.PushCommand("Ping",null,null,user_cb,true,false);
	}
	,PingSession: function(user_cb) {
		return this.PushCommand("PingSession",null,null,user_cb,false,false);
	}
	,UniverseCreate: function(universe,isKeycloak,user_cb) {
		var param = new gms_VertxCmd_$MessageData();
		param.UniverseName = universe;
		if(isKeycloak) {
			param.UniverseIDP = "Keycloak";
		}
		return this.PushCommand("UniverseCreate",param,null,user_cb,true,false);
	}
	,ApplicationCreate: function(universe,application,user_cb) {
		var param = new gms_VertxCmd_$MessageData();
		param.UniverseName = universe;
		param.ApplicationName = application;
		return this.PushCommand("ApplicationCreate",param,null,user_cb,true,false);
	}
	,UniverseDelete: function(universe,user_cb) {
		var param = new gms_VertxCmd_$MessageData();
		param.UniverseName = universe;
		return this.PushCommand("AdminDeleteUniverse",param,null,user_cb,true,false);
	}
	,UniverseAppGet: function(universe,app,user_cb) {
		var param = new gms_VertxCmd_$MessageData();
		param.UniverseName = universe;
		param.ApplicationName = app;
		return this.PushCommand("UniverseAppGet",param,null,user_cb,true,false);
	}
	,UserMeetingActivityGetInfos: function(meeting_id,user_cb) {
		var param = new gms_VertxCmd_$MessageData();
		param.MeetingID = meeting_id;
		return this.PushCommand("UserMeetingActivityGetInfos",param,null,user_cb,true,false);
	}
	,AdminDeleteUser: function(user_universe,user_id,OR_login,OR_mail,user_cb) {
		var param = new gms_VertxCmd_$MessageData();
		param.UniverseName = user_universe;
		param.UserID = user_id;
		param.UserLogin = OR_login;
		param.UserMail = OR_mail;
		return this.PushCommand("AdminDeleteUser",param,null,user_cb,true,false);
	}
	,UserAdd: function(info,user_cb) {
		var param = new gms_VertxCmd_$MessageData();
		param.UniverseName = gms_VertxCmd.IsValid(info.Universe) ? info.Universe : this.UniverseName;
		param.UserLogin = info.Login;
		param.UserPassword = info.Password;
		param.UserMail = info.Mail;
		param.UserPseudo = info.Pseudo;
		param.UserLastName = info.LastName;
		param.UserFirstName = info.FirstName;
		return this.PushCommand("UserAdd",param,null,user_cb,true,false);
	}
	,UserAddSaml: function(universe,saml_response,user_cb) {
		var param = new gms_VertxCmd_$MessageData();
		param.UniverseName = gms_VertxCmd.IsValid(universe) ? universe : this.UniverseName;
		param.UserSamlResponse = saml_response;
		return this.PushCommand("UserAdd",param,null,user_cb,true,false);
	}
	,UserAnonymousAdd: function(universe,user_cb) {
		var param = new gms_VertxCmd_$MessageData();
		param.UniverseName = gms_VertxCmd.IsValid(universe) ? universe : this.UniverseName;
		return this.PushCommand("UserAnonymousAdd",param,null,user_cb,true,false);
	}
	,UserUpdateInfo: function(info,user_cb) {
		var param = new gms_VertxCmd_$MessageData();
		param.UserMail = info.Mail;
		param.UserPseudo = info.Pseudo;
		param.UserLastName = info.LastName;
		param.UserFirstName = info.FirstName;
		return this.PushCommand("UserUpdateInfo",param,null,user_cb,true,false);
	}
	,UserUpdatePassword: function(password,user_cb) {
		var param = new gms_VertxCmd_$MessageData();
		param.UserPassword = password;
		return this.PushCommand("UserUpdatePassword",param,null,user_cb,true,false);
	}
	,UserUpdatePassword_String_String_String_ActionBooleanStringMessageData: function(universe,mail,url,user_cb) {
		var param = new gms_VertxCmd_$MessageData();
		param.UniverseName = universe;
		param.UserMail = mail;
		param.Url = url;
		return this.PushCommand("UserUpdatePassword",param,null,user_cb,true,false);
	}
	,UserGetInfo: function(user_cb) {
		return this.PushCommand("UserGetInfo",null,null,user_cb,true,false);
	}
	,UserConnect: function(universe,application,login,pwd,user_cb) {
		var _gthis = this;
		if(this.IsSessionValidOrInProgress()) {
			return false;
		}
		var param = new gms_VertxCmd_$MessageData();
		param.UniverseName = universe;
		param.ApplicationName = application;
		param.UserLogin = login;
		param.UserPassword = pwd;
		this.UpdateSystemInfos(function(x) {
			if(_gthis.SystemInfos != null) {
				param.DataArray = [];
				param.DataArray.push(_gthis.SystemInfos.Stringify());
			}
			_gthis.Log("^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^");
			_gthis.Log("UserConnect 2f: " + (param != null ? gms_tool_Json.stringify(param) : "{}"));
			_gthis.Log("^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^");
			_gthis.PushCommand("UserConnect",param,$bind(_gthis,_gthis.UserConnectCB),user_cb,true,false);
		});
		return true;
	}
	,UserConnectKeycloak: function(universe,application,keycloak_token,user_cb) {
		var _gthis = this;
		if(this.IsSessionValidOrInProgress()) {
			return false;
		}
		var param = new gms_VertxCmd_$MessageData();
		param.UniverseName = universe;
		param.ApplicationName = application;
		param.UserLogin = null;
		param.UserPassword = keycloak_token;
		this.UpdateSystemInfos(function(x) {
			if(_gthis.SystemInfos != null) {
				param.DataArray = [];
				param.DataArray.push(_gthis.SystemInfos.Stringify());
			}
			_gthis.Log("^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^");
			_gthis.Log("UserConnectKeycloak on " + universe + " / " + application);
			_gthis.Log("^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^");
			_gthis.PushCommand("UserConnect",param,$bind(_gthis,_gthis.UserConnectCB),user_cb,true,false);
		});
		return true;
	}
	,UserConnectWithGmsToken: function(universe,app,gms_token,user_cb) {
		var _gthis = this;
		var param = new gms_VertxCmd_$MessageData();
		param.UniverseName = universe;
		param.ApplicationName = app;
		param.Session = gms_token;
		this.UpdateSystemInfos(function(x) {
			if(_gthis.SystemInfos != null) {
				param.DataArray = [];
				param.DataArray.push(_gthis.SystemInfos.Stringify());
			}
			_gthis.PushCommand("UserConnect",param,$bind(_gthis,_gthis.UserConnectCB),user_cb,true,false);
		});
		return true;
	}
	,UserReConnect: function(user_cb) {
		if(!this.IsSessionValid()) {
			this.Log("Can't reconnect : Invalid SessionToken");
			return false;
		}
		gms_system_Cs2Hx.RemoveAll(this.PendingMessages,function(x) {
			return gms_system_Cs2Hx.Equals_String(x.Msg.Name,"UserConnect");
		});
		return this.UserConnectWithGmsToken(this.UniverseName,this.ApplicationName,this.getSessionToken(),user_cb);
	}
	,UserConnectAdd: function(universe,application,login,pwd,user_cb) {
		var _gthis = this;
		if(this.IsSessionValidOrInProgress()) {
			return false;
		}
		return this.UserConnect(universe,application,login,pwd,function(status,status_msg,data) {
			if(status) {
				user_cb(status,status_msg,data);
			} else if(gms_system_Cs2Hx.Equals_String(status_msg,"USER_NOT_FOUND")) {
				var info = new gms_VertxCmd_$UserInfo();
				info.Universe = universe;
				info.Login = login;
				info.Password = pwd;
				info.Mail = login + "@gms.succubus.fr";
				info.Pseudo = login + "_Pseudo";
				info.LastName = login + "_Lastname";
				info.FirstName = login + "_FirstName";
				_gthis.UserAdd(info,function(status2,status_msg2,data2) {
					if(status2) {
						_gthis.UserConnect(universe,application,login,pwd,user_cb);
					} else {
						user_cb(status2,status_msg2,data2);
					}
				});
			}
		});
	}
	,UserAnonymousConnectAdd: function(universe,application,user_cb) {
		var _gthis = this;
		return this.UserAnonymousAdd(universe,function(status,status_msg,data) {
			if(status && data != null) {
				_gthis.UserConnect(universe,application,data.UserLogin,data.UserPassword,function(status2,status_msg2,data2) {
					if(data2 != null) {
						data2.UserLogin = data.UserLogin;
						data2.UserPassword = data.UserPassword;
					}
					if(user_cb != null) {
						user_cb(status2,status_msg2,data2);
					}
				});
			} else {
				user_cb(status,status_msg,data);
			}
		});
	}
	,UserConnectCB: function(status,msg,data) {
		if(status && gms_VertxCmd.IsValid(data.Session)) {
			this.UniverseName = data.UniverseName;
			this.ApplicationName = data.ApplicationName;
			this.UserLogin = data.UserLogin;
			this.UserPseudo = data.UserPseudo;
			this.setSessionToken(data.Session);
			data.Session = null;
		}
	}
	,UserDisconnect: function(user_cb) {
		return this.PushCommand("UserDisconnect",null,$bind(this,this.UserDisconnectCB),user_cb,true,false);
	}
	,UserDisconnectCB: function(status,msg,data) {
		this.ClearSession();
	}
	,ClearSession: function() {
		this.UniverseName = null;
		this.ApplicationName = null;
		this.UserLogin = null;
		this.UserPseudo = null;
		this.setSessionToken(null);
	}
	,AdminGetUniverses: function(user_cb) {
		return this.PushCommand("AdminGetUniverses",null,null,user_cb,true,false);
	}
	,AdminGetApplications: function(universe,user_cb) {
		var param = new gms_VertxCmd_$MessageData();
		param.UniverseName = universe;
		return this.PushCommand("AdminGetApplications",param,null,user_cb,true,false);
	}
	,AdminGetRoles: function(universe,user_cb) {
		var param = new gms_VertxCmd_$MessageData();
		param.UniverseName = universe;
		return this.PushCommand("AdminGetRoles",param,null,user_cb,true,false);
	}
	,AdminGetUsers: function(universe,user_cb) {
		var param = new gms_VertxCmd_$MessageData();
		param.UniverseName = universe;
		return this.PushCommand("AdminGetUsers",param,null,user_cb,true,false);
	}
	,UserApplicationGetConfigs: function(user_cb) {
		return this.PushCommand("UserApplicationGetConfigs",null,null,user_cb,true,false);
	}
	,MeetingCreate: function(meeting_name,meeting_password,meeting_config,user_cb) {
		var param = new gms_VertxCmd_$MessageData();
		param.MeetingName = meeting_name;
		param.MeetingPassword = meeting_password;
		if(meeting_config != null) {
			param.DataArray = [];
			param.DataArray.push(meeting_config);
		}
		return this.PushCommand("MeetingCreate",param,null,user_cb,true,false);
	}
	,UserMeetingGetConfig: function(meeting_id,user_cb) {
		var param = new gms_VertxCmd_$MessageData();
		param.MeetingID = meeting_id;
		return this.PushCommand("UserMeetingGetConfig",param,null,user_cb,true,false);
	}
	,UserMeetingGetFields: function(meeting_id,fields,user_cb) {
		var param = new gms_VertxCmd_$MessageData();
		param.MeetingID = meeting_id;
		param.DataArray = fields;
		return this.PushCommand("UserMeetingGetFields",param,null,user_cb,true,false);
	}
	,UserMeetingGetScores: function(meeting_id,user_cb) {
		var param = new gms_VertxCmd_$MessageData();
		param.MeetingID = meeting_id;
		return this.PushCommand("UserMeetingGetScores",param,null,user_cb,true,false);
	}
	,UserMeetingSetScores: function(meeting_id,scores,optional_score_id,user_cb) {
		var param = new gms_VertxCmd_$MessageData();
		param.MeetingID = meeting_id;
		param.DataArray = [];
		param.DataArray.push(scores);
		if(optional_score_id != null) {
			param.DataArray.push(optional_score_id);
		}
		return this.PushCommand("UserMeetingSetScores",param,null,user_cb,true,false);
	}
	,MeetingGetEventScores: function(meeting_id,user_id,user_cb) {
		var param = new gms_VertxCmd_$MessageData();
		param.MeetingID = meeting_id;
		param.UserID = user_id;
		return this.PushCommand("MeetingGetEventScores",param,null,user_cb,true,false);
	}
	,MeetingDestroy: function(meeting_id,user_cb) {
		var param = new gms_VertxCmd_$MessageData();
		param.MeetingID = meeting_id;
		return this.PushCommand("MeetingDestroy",param,null,user_cb,true,false);
	}
	,MeetingAddUser: function(meeting_id,meeting_password,user_login,user_cb) {
		var param = new gms_VertxCmd_$MessageData();
		param.MeetingID = meeting_id;
		param.MeetingPassword = meeting_password;
		param.AdminLogins = [];
		param.AdminLogins.push(user_login);
		return this.PushCommand("MeetingAddUser",param,null,user_cb,true,false);
	}
	,MeetingAddUserWithCode: function(meeting_code,user_login,user_cb) {
		var param = new gms_VertxCmd_$MessageData();
		param.MeetingCode = meeting_code;
		param.AdminLogins = [];
		param.AdminLogins.push(user_login);
		return this.PushCommand("MeetingAddUser",param,null,user_cb,true,false);
	}
	,MeetingGetAdministeredList: function(user_cb) {
		return this.PushCommand("MeetingGetAdministeredList",null,null,user_cb,true,false);
	}
	,MeetingGetInfos: function(meeting_id,user_cb) {
		var param = new gms_VertxCmd_$MessageData();
		param.MeetingID = meeting_id;
		return this.PushCommand("MeetingGetInfos",param,null,user_cb,true,false);
	}
	,MeetingGetCode: function(meeting_id,user_cb) {
		var param = new gms_VertxCmd_$MessageData();
		param.MeetingID = meeting_id;
		return this.PushCommand("MeetingGetCode",param,null,user_cb,true,false);
	}
	,UserMeetingConnect: function(meeting_id,user_cb) {
		var param = new gms_VertxCmd_$MessageData();
		param.MeetingID = meeting_id;
		return this.PushCommand("UserMeetingConnect",param,null,user_cb,true,false);
	}
	,UserMeetingGetConnected: function(meeting_id,user_cb) {
		var param = new gms_VertxCmd_$MessageData();
		param.MeetingID = meeting_id;
		return this.PushCommand("UserMeetingGetConnected",param,null,user_cb,true,false);
	}
	,UserMeetingDisconnect: function(meeting_id,user_cb) {
		var param = new gms_VertxCmd_$MessageData();
		param.MeetingID = meeting_id;
		return this.PushCommand("UserMeetingDisconnect",param,null,user_cb,true,false);
	}
	,UserMeetingRemove: function(meeting_id,user_cb) {
		var param = new gms_VertxCmd_$MessageData();
		param.MeetingID = meeting_id;
		return this.PushCommand("UserMeetingRemove",param,null,user_cb,true,false);
	}
	,UserMeetingSendToAll: function(meeting_id,meeting_message,to_admins_only,user_cb) {
		if(!gms_VertxCmd.IsValid(meeting_id) || !gms_VertxCmd.IsValid(meeting_message)) {
			return false;
		}
		var param = new gms_VertxCmd_$MessageData();
		param.MeetingID = meeting_id;
		param.DataArray = [];
		param.DataArray.push(meeting_message);
		param.DataArray.push(to_admins_only ? "1" : "0");
		return this.PushCommand("UserMeetingSendToAll",param,null,user_cb,true,false);
	}
	,UserMeetingGetList: function(user_cb) {
		return this.PushCommand("UserMeetingGetList",null,null,user_cb,true,false);
	}
	,UserMeetingCommand: function(meeting_id,command,data,user_cb) {
		var param = new gms_VertxCmd_$MessageData();
		param.MeetingID = meeting_id;
		param.MeetingCommands = [];
		param.MeetingCommands.push(command);
		param.DataArray = [];
		param.DataArray.push(data);
		return this.PushCommand("UserMeetingCommand",param,null,user_cb,true,false);
	}
	,UserMeetingActivityIsValid: function(meeting_id,user_cb) {
		var param = new gms_VertxCmd_$MessageData();
		param.MeetingID = meeting_id;
		param.MeetingCommands = [];
		param.MeetingCommands.push("Ping");
		param.DataArray = [];
		param.DataArray.push("");
		return this.PushCommand("UserMeetingCommand",param,null,user_cb,true,false);
	}
	,UserMeetingRiddleCommand: function(meeting_id,riddle,user_cb) {
		return this.UserMeetingCommand(meeting_id,"ComponentMeetingRiddle",riddle,user_cb);
	}
	,MeetingSequenceSet: function(meeting_id,sequence,user_cb) {
		var param = new gms_VertxCmd_$MessageData();
		param.MeetingID = meeting_id;
		if(sequence != null) {
			param.DataArray = [];
			param.DataArray.push(sequence);
		}
		return this.PushCommand("MeetingSequenceSet",param,null,user_cb,true,false);
	}
	,UserMeetingSequencerCommand: function(meeting_id,sequencer_cmd,user_cb) {
		return this.UserMeetingCommand(meeting_id,"ComponentMeetingSequencerController",sequencer_cmd,user_cb);
	}
	,UserMeetingFindOpened: function(meeting_type,user_cb) {
		var param = new gms_VertxCmd_$MessageData();
		param.MeetingType = meeting_type == null ? "Generic" : meeting_type;
		return this.PushCommand("UserMeetingFindOpened",param,null,user_cb,true,false);
	}
	,UserEventsAdd: function(event_array,user_cb) {
		var param = new gms_VertxCmd_$MessageData();
		param.DataArray = event_array;
		return this.PushCommand("UserEventsAdd",param,null,user_cb,false,false);
	}
	,UserUpdateCustomData: function(custom_data,user_cb) {
		var param = new gms_VertxCmd_$MessageData();
		param.DataArray = [];
		param.DataArray.push(custom_data);
		return this.PushCommand("UserUpdateCustomData",param,null,user_cb,true,false);
	}
	,UserApplicationSave_Create: function(name,user_cb) {
		var param = new gms_VertxCmd_$MessageData();
		param.AppSaveName = name;
		return this.PushCommand("UserApplicationSave_Create",param,null,user_cb,true,false);
	}
	,UserApplicationSave_Destroy: function(id,user_cb) {
		var param = new gms_VertxCmd_$MessageData();
		param.AppSaveID = id;
		return this.PushCommand("UserApplicationSave_Destroy",param,null,user_cb,true,false);
	}
	,UserApplicationSave_GetActions: function(id,user_cb) {
		var param = new gms_VertxCmd_$MessageData();
		param.AppSaveID = id;
		return this.PushCommand("UserApplicationSave_GetActions",param,null,user_cb,true,false);
	}
	,UserApplicationSave_GetCustomData: function(id,user_cb) {
		var param = new gms_VertxCmd_$MessageData();
		param.AppSaveID = id;
		return this.PushCommand("UserApplicationSave_GetCustomData",param,null,user_cb,true,false);
	}
	,UserApplicationSave_GetList: function(user_cb) {
		return this.PushCommand("UserApplicationSave_GetList",null,null,user_cb,true,false);
	}
	,UserApplicationSave_PushActions: function(id,actions,user_cb) {
		var param = new gms_VertxCmd_$MessageData();
		param.AppSaveID = id;
		param.DataArray = actions;
		return this.PushCommand("UserApplicationSave_PushActions",param,null,user_cb,true,false);
	}
	,UserApplicationSave_ClearActions: function(id,user_cb) {
		var param = new gms_VertxCmd_$MessageData();
		param.AppSaveID = id;
		return this.PushCommand("UserApplicationSave_ClearActions",param,null,user_cb,true,false);
	}
	,UserApplicationSave_SetCustomData: function(id,data,user_cb) {
		var param = new gms_VertxCmd_$MessageData();
		param.AppSaveID = id;
		param.DataArray = [];
		param.DataArray.push(data);
		return this.PushCommand("UserApplicationSave_SetCustomData",param,null,user_cb,true,false);
	}
	,AdminGetCollection: function(collection,query,user_cb) {
		var param = new gms_VertxCmd_$MessageData();
		param.CollectionName = collection;
		if(gms_VertxCmd.IsValid(query)) {
			param.DataArray = [];
			param.DataArray.push(query);
		}
		return this.PushCommand("AdminGetCollection",param,null,user_cb,true,false);
	}
	,AnalyticGetInfos: function(query,user_cb) {
		var param = new gms_VertxCmd_$MessageData();
		if(gms_VertxCmd.IsValid(query)) {
			param.DataArray = [];
			param.DataArray.push(query);
		}
		return this.PushCommand("AnalyticGetInfos",param,null,user_cb,true,false);
	}
	,PushCommand: function(name,param,cmd_cb,user_cb,need_reply,block_until_reply) {
		if(!need_reply) {
			block_until_reply = false;
		}
		var gms_token = param != null && gms_VertxCmd.IsValid(param.Session) ? param.Session : this.getSessionToken();
		this.PendingMessages.push(new gms_VertxCmd_$MessageSlot(new gms_VertxCmd_$Message(name,"ClientCmd","" + this.SendCounter++,gms_token,param,need_reply),cmd_cb,user_cb,block_until_reply));
		this.LogPendingMessages();
		return true;
	}
	,LogPendingMessages: function() {
		this.Log("**********************************************");
		this.Log(" PendingMessages, Time : " + gms_tool_Timer.stamp());
		this.Log("**********************************************");
		var _g = 0;
		var _g1 = this.PendingMessages;
		while(_g < _g1.length) {
			var s = _g1[_g];
			++_g;
			this.Log("- " + s.DebugLog());
		}
		this.Log("**********************************************");
	}
	,UpdateCB: function(t,dt) {
		if(!this.Net.IsConnected()) {
			return;
		}
		if(this.PingTimer > 0 && this.Time_NextPing < t) {
			if(this.Time_NextPing > 0) {
				this.Ping(null);
			}
			this.Time_NextPing = t + this.PingTimer;
		}
		if(this.PingSessionTimer > 0 && this.Time_NextPingSession < t) {
			if(this.Time_NextPingSession > 0) {
				this.PingSession(null);
			}
			this.Time_NextPingSession = t + this.PingSessionTimer;
		}
		if(this.PendingMessages.length <= 0) {
			return;
		}
		var RemoveList = [];
		var show_log = false;
		var i = 0;
		while(i < this.PendingMessages.length) {
			var slot = this.PendingMessages[i];
			if(slot.IsBlocking()) {
				break;
			} else if(slot.TimeOut()) {
				RemoveList.push(i);
				show_log = true;
				if(slot.MsgCB != null) {
					slot.MsgCB(false,"TimeOut",null);
				}
				if(slot.UserCB != null) {
					slot.UserCB(false,"TimeOut",null);
				}
			} else if(!slot.Sent()) {
				if(!gms_VertxCmd.IsValid(slot.Msg.Session)) {
					slot.Msg.Session = this.getSessionToken();
				}
				var net_msg = slot.Msg.Stringify();
				this.Net.SendText(net_msg);
				slot.SetTimer();
				show_log = true;
				if(slot.HasReply()) {
					if(slot.IsBlocking()) {
						break;
					}
				} else {
					RemoveList.push(i);
				}
			}
			++i;
		}
		var i = 0;
		while(i < RemoveList.length) {
			this.PendingMessages.splice(RemoveList[i] - i,1);
			++i;
		}
		if(show_log) {
			this.LogPendingMessages();
		}
	}
	,OnMessageReceived: function(msg) {
		this.Log("----------------------------------------");
		this.Log("MESSAGE RECEIVED :");
		this.Log(msg);
		this.Log("----------------------------------------");
		if(!gms_VertxCmd.IsValid(msg)) {
			return;
		}
		var M = gms_VertxCmd_$Message.Parse(msg);
		this.Log("- Name : " + M.Name);
		this.Log("- Status : " + (M.Status == null ? "null" : "" + M.Status));
		if(M.StatusMsg != null) {
			this.Log("- StatusMessage : " + M.StatusMsg);
		}
		if(gms_system_Cs2Hx.Equals_String(M.Type,"ClientCmdResult") || gms_system_Cs2Hx.Equals_String(M.Type,"ClientCmdResultSlice")) {
			this.Log("- Client Result");
			var slot = null;
			if(M.ID != null) {
				slot = gms_tool_Util.Find(this.PendingMessages,function(x) {
					return x.Msg.ID == M.ID;
				});
			}
			if(slot != null) {
				if(gms_system_Cs2Hx.Equals_String(M.Type,"ClientCmdResult")) {
					HxOverrides.remove(this.PendingMessages,slot);
				} else {
					this.Log("- SLICE");
					slot.SetTimer();
				}
				this.Log("----------------------------------------");
				if(slot.MsgCB != null) {
					slot.MsgCB(M.Status,M.StatusMsg,M.Data);
				}
				if(slot.UserCB != null) {
					slot.UserCB(M.Status,M.StatusMsg,M.Data);
				}
			} else {
				this.Log("- ERROR: Slot not found");
				this.Log("----------------------------------------");
				this.Assert(false);
			}
		} else if(gms_system_Cs2Hx.Equals_String(M.Type,"ServerCmd")) {
			this.Log("----------------------------------------");
			this.Log("-- ServerCmd received :");
			if(gms_system_Cs2Hx.Equals_String(M.Name,"MeetingMessage")) {
				if(M.Data != null && M.Data.DataArray != null && M.Data.MeetingID != null) {
					this.SIG_MeetingMessage.Send(M.Data.MeetingID,M.Data.UserID,M.Data.DataArray[0]);
				}
			}
			this.Log("----------------------------------------");
		} else {
			this.Log("----------------------------------------");
			this.Log("-- Unknow data received :");
			this.Log("----------------------------------------");
		}
	}
	,OnSocketStatusChanged: function(status,msg) {
		var _gthis = this;
		this.Log("OnSocketStatusChanged : " + (status == null ? "null" : "" + status) + (msg != null ? ", " + msg : ""));
		this.SIG_SocketConnection.Send(status,msg);
		if(status && this.IsSessionValid()) {
			this.UserReConnect(function(s,m,d) {
				_gthis.Log("UserReConnect : " + (s == null ? "null" : "" + s) + " (" + m + ")");
			});
		}
	}
	,UpdateSystemInfos: function(cb) {
	}
	,__class__: gms_VertxCmd
};
var gms_VertxClient = $hx_exports["gms"]["VertxClient"] = function() {
	gms_VertxCmd.call(this);
	this.sequencerCmdHelper = new gms_VertxCmd_$SequencerCommand();
};
gms_VertxClient.__name__ = true;
gms_VertxClient.CreateVertxClient = function(ip,port) {
	if(gms_VertxClient.UpdateTimer == null) {
		gms_tool_Timer.StartTime = gms_tool_Timer.stamp();
		gms_UpdateManager.cctor();
		gms_VertxClient.UpdateTimer = new haxe_Timer(100);
		gms_VertxClient.UpdateTimer.run = gms_UpdateManager.Update;
	}
	var client = new gms_VertxClient();
	client.CommonInit(ip,port);
	return client;
};
gms_VertxClient.PasswordEncode = function(pwd) {
	if(pwd != null) {
		return haxe_crypto_Md5.encode(pwd);
	} else {
		return null;
	}
};
gms_VertxClient.GetMeetingID = function(meeting_list,meeting_login) {
	var _g = 0;
	var _g1 = Reflect.fields(meeting_list);
	while(_g < _g1.length) {
		var id = _g1[_g];
		++_g;
		if(Reflect.field(meeting_list,id) == meeting_login) {
			return id;
		}
	}
	return null;
};
gms_VertxClient.GetString = function(data) {
	if(data == null || data.DataArray == null || data.DataArray.length <= 0 || data.DataArray[0].length <= 0) {
		return null;
	}
	return data.DataArray[0];
};
gms_VertxClient.GetJsonObject = function(data) {
	if(data == null || data.DataArray == null || data.DataArray.length <= 0 || data.DataArray[0].length <= 0) {
		return { };
	}
	return JSON.parse(data.DataArray[0]);
};
gms_VertxClient.GetJsonArray = function(data) {
	if(data == null || data.DataArray == null || data.DataArray.length <= 0) {
		return [];
	}
	var res = [];
	var _g = 0;
	var _g1 = data.DataArray;
	while(_g < _g1.length) {
		var d = _g1[_g];
		++_g;
		res.push(JSON.parse(d));
	}
	return res;
};
gms_VertxClient.__super__ = gms_VertxCmd;
gms_VertxClient.prototype = $extend(gms_VertxCmd.prototype,{
	UpdateSystemInfos: function(done) {
		var INFO = this.SystemInfos = new gms_VertxCmd_$SystemInfo();
		INFO.Os = "";
		INFO.OsVersion = "";
		INFO.PhysicalPixelPerInch = 0.0;
		INFO.PhysicalDiagonalSizeInInches = 0.0;
		INFO.PhysicalRatio = 1.7777777777777777;
		INFO.Os = "Web";
		INFO.Browser = $global.navigator.vendor;
		INFO.BrowserVersion = $global.navigator.vendorSub;
		done(true);
	}
	,SendEvent: function(event,user_cb) {
		this.UserEventsAdd([JSON.stringify(event)],user_cb);
	}
	,UserConnectNonEncryptedToken: function(universe,application,token,user_cb) {
		if(this.IsSessionValidOrInProgress()) {
			return false;
		}
		var param = new gms_VertxCmd_$MessageData();
		param.UniverseName = universe;
		param.ApplicationName = application;
		param.UserLogin = null;
		param.UserPassword = token;
		this.Log("^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^");
		this.Log("UserConnectNonEncryptedToken on " + universe + " / " + application);
		this.Log("^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^");
		return this.PushCommand("UserConnectNonEncryptedToken",param,$bind(this,this.UserConnectCB),user_cb,true,true);
	}
	,UserUpdatePasswordKeycloak: function(universe,application,token,new_password,user_cb) {
		var param = new gms_VertxCmd_$MessageData();
		param.UniverseName = universe;
		param.ApplicationName = application;
		param.UserLogin = token;
		param.UserPassword = new_password;
		this.Log("^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^");
		this.Log("UserUpdatePasswordKeycloak on " + universe + " / " + application);
		this.Log("^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^");
		return this.PushCommand("UserUpdatePasswordKeycloak",param,null,user_cb,true,true);
	}
	,__class__: gms_VertxClient
});
var gms_VertxCmd_$Message = function(name,type,id,session_id,data,reply) {
	this.Status = false;
	this.Reply = false;
	this.Name = name;
	this.Type = type;
	this.ID = id;
	this.Session = session_id;
	this.Data = data;
	this.Reply = reply;
	this.Status = false;
	this.StatusMsg = null;
};
gms_VertxCmd_$Message.__name__ = true;
gms_VertxCmd_$Message.Parse = function(msg) {
	return gms_tool_Json.parse(msg,gms_VertxCmd_$Message);
};
gms_VertxCmd_$Message.prototype = {
	Stringify: function() {
		return gms_tool_Json.stringify(this);
	}
	,__class__: gms_VertxCmd_$Message
};
var gms_VertxCmd_$MessageData = function() {
	this.DocumentsFound = 0;
};
gms_VertxCmd_$MessageData.__name__ = true;
gms_VertxCmd_$MessageData.prototype = {
	__class__: gms_VertxCmd_$MessageData
};
var gms_VertxCmd_$MessageSlot = function(cmd,cmd_cb,user_cb,block) {
	this.BlockUntilReply = false;
	this.SendTime = 0;
	this.Msg = cmd;
	this.MsgCB = cmd_cb;
	this.UserCB = user_cb;
	this.BlockUntilReply = block;
	this.SendTime = 0;
};
gms_VertxCmd_$MessageSlot.__name__ = true;
gms_VertxCmd_$MessageSlot.prototype = {
	HasReply: function() {
		return this.Msg.Reply;
	}
	,SetTimer: function() {
		var n = 1;
		var d = 1000;
		var epsilon = n / d;
		this.SendTime = gms_tool_Timer.stamp();
		this.SendTime = this.SendTime < epsilon ? epsilon : this.SendTime;
	}
	,IsBlocking: function() {
		if(!this.Msg.Reply || !this.BlockUntilReply || this.SendTime <= 0) {
			return false;
		}
		return gms_tool_Timer.stamp() - this.SendTime < 5;
	}
	,TimeOut: function() {
		if(this.SendTime > 0) {
			return gms_tool_Timer.stamp() - this.SendTime > 10;
		} else {
			return false;
		}
	}
	,TimeLeft: function(time_max) {
		if(this.SendTime > 0) {
			var dt = gms_tool_Timer.stamp() - this.SendTime;
			if(dt < time_max) {
				return time_max - dt;
			} else {
				return 0;
			}
		} else {
			return 0;
		}
	}
	,Sent: function() {
		return this.SendTime > 0;
	}
	,DebugLog: function() {
		var res = this.Msg.Name + " :\tSent: " + Std.string(this.Sent()) + ",\tHasReply: " + Std.string(this.HasReply());
		if(this.Sent()) {
			res = res + ",\tBlock: " + this.TimeLeft(5) + "s. ,\tTimeOut: " + this.TimeLeft(10) + "s.";
		}
		return res;
	}
	,__class__: gms_VertxCmd_$MessageSlot
};
var gms_VertxCmd_$SequencerCommand = function() {
};
gms_VertxCmd_$SequencerCommand.__name__ = true;
gms_VertxCmd_$SequencerCommand.SetPeriod = function(p) {
	return "{\"SetPeriod\":" + p + "}";
};
gms_VertxCmd_$SequencerCommand.StartPeriod = function() {
	return "{\"StartPeriod\":0}";
};
gms_VertxCmd_$SequencerCommand.UpdateSpeedFactor = function(speed) {
	return "{\"UpdateSpeedFactor\":" + speed + "}";
};
gms_VertxCmd_$SequencerCommand.PausePeriod = function() {
	return "{\"PausePeriod\":0}";
};
gms_VertxCmd_$SequencerCommand.StopPeriod = function() {
	return "{\"StopPeriod\":0}";
};
gms_VertxCmd_$SequencerCommand.StopSequence = function() {
	return "{\"StopSequence\":0}";
};
gms_VertxCmd_$SequencerCommand.GetInfos = function() {
	return "{\"GetInfos\":0}";
};
gms_VertxCmd_$SequencerCommand.prototype = {
	__class__: gms_VertxCmd_$SequencerCommand
};
var gms_VertxCmd_$SystemInfo = function() {
	this.Longitude = 0;
	this.Latitude = 0;
	this.PhysicalRatio = 0;
	this.PhysicalDiagonalSizeInInches = 0;
	this.PhysicalPixelPerInch = 0;
	this.DisplayHeight = 0;
	this.DisplayWidth = 0;
};
gms_VertxCmd_$SystemInfo.__name__ = true;
gms_VertxCmd_$SystemInfo.prototype = {
	Stringify: function() {
		return gms_tool_Json.stringify(this);
	}
	,__class__: gms_VertxCmd_$SystemInfo
};
var gms_VertxCmd_$UserInfo = function() {
};
gms_VertxCmd_$UserInfo.__name__ = true;
gms_VertxCmd_$UserInfo.prototype = {
	__class__: gms_VertxCmd_$UserInfo
};
var gms_module_analytics_AnalyticsApi = $hx_exports["gms"]["module"]["analytics"]["AnalyticsApi"] = function() {
};
gms_module_analytics_AnalyticsApi.__name__ = true;
gms_module_analytics_AnalyticsApi.prototype = {
	init: function(vertxClient) {
		this.client = vertxClient;
	}
	,prepareData: function(data) {
		return JSON.stringify(data);
	}
	,send: function(data,callback) {
		if(this.client == null) {
			return false;
		}
		this.client.UserEventsAdd([this.prepareData(data)],callback);
		return true;
	}
	,sendMultiple: function(datas,callback) {
		if(this.client == null) {
			return false;
		}
		var preparedDatas = [];
		var _g = 0;
		while(_g < datas.length) {
			var data = datas[_g];
			++_g;
			preparedDatas.push(this.prepareData(data));
		}
		this.client.UserEventsAdd(preparedDatas,callback);
		return true;
	}
	,navigationLeave: function(id,callback) {
		var e = gms_module_analytics_AnalyticsEvent.NAVIGATION;
		var e1 = gms_module_analytics_NavigationValue.LEAVE;
		var data = { type : $hxEnums[e.__enum__].__constructs__[e._hx_index], id : id, value : $hxEnums[e1.__enum__].__constructs__[e1._hx_index]};
		return this.send(data,callback);
	}
	,navigationEnter: function(id,callback) {
		var e = gms_module_analytics_AnalyticsEvent.NAVIGATION;
		var e1 = gms_module_analytics_NavigationValue.ENTER;
		var data = { type : $hxEnums[e.__enum__].__constructs__[e._hx_index], id : id, value : $hxEnums[e1.__enum__].__constructs__[e1._hx_index]};
		return this.send(data,callback);
	}
	,navigationLeaveAndEnter: function(leaveId,enterId,callback) {
		var e = gms_module_analytics_AnalyticsEvent.NAVIGATION;
		var e1 = gms_module_analytics_NavigationValue.LEAVE;
		var leaveData = { type : $hxEnums[e.__enum__].__constructs__[e._hx_index], id : leaveId, value : $hxEnums[e1.__enum__].__constructs__[e1._hx_index]};
		var e = gms_module_analytics_AnalyticsEvent.NAVIGATION;
		var e1 = gms_module_analytics_NavigationValue.ENTER;
		var enterData = { type : $hxEnums[e.__enum__].__constructs__[e._hx_index], id : enterId, value : $hxEnums[e1.__enum__].__constructs__[e1._hx_index]};
		return this.sendMultiple([leaveData,enterData],callback);
	}
	,score: function(id,value,callback) {
		var e = gms_module_analytics_AnalyticsEvent.SCORE;
		var data = { type : $hxEnums[e.__enum__].__constructs__[e._hx_index], id : id, value : value};
		return this.send(data,callback);
	}
	,choice: function(id,answerId,callback) {
		var e = gms_module_analytics_AnalyticsEvent.CHOICE;
		var data = { type : $hxEnums[e.__enum__].__constructs__[e._hx_index], id : id, value : answerId};
		return this.send(data,callback);
	}
	,action: function(id,x,y,callback) {
		var coord = x + "/" + y;
		var e = gms_module_analytics_AnalyticsEvent.ACTION;
		var data = { type : $hxEnums[e.__enum__].__constructs__[e._hx_index], id : id, value : coord};
		return this.send(data,callback);
	}
	,contentShow: function(id,callback) {
		var e = gms_module_analytics_AnalyticsEvent.CONTENT;
		var e1 = gms_module_analytics_ContentValue.SHOW;
		var data = { type : $hxEnums[e.__enum__].__constructs__[e._hx_index], id : id, value : $hxEnums[e1.__enum__].__constructs__[e1._hx_index]};
		return this.send(data,callback);
	}
	,contentHide: function(id,callback) {
		var e = gms_module_analytics_AnalyticsEvent.CONTENT;
		var e1 = gms_module_analytics_ContentValue.HIDE;
		var data = { type : $hxEnums[e.__enum__].__constructs__[e._hx_index], id : id, value : $hxEnums[e1.__enum__].__constructs__[e1._hx_index]};
		return this.send(data,callback);
	}
	,contentInterrupted: function(id,callback) {
		var e = gms_module_analytics_AnalyticsEvent.CONTENT;
		var e1 = gms_module_analytics_ContentValue.INTERRUPTED;
		var data = { type : $hxEnums[e.__enum__].__constructs__[e._hx_index], id : id, value : $hxEnums[e1.__enum__].__constructs__[e1._hx_index]};
		return this.send(data,callback);
	}
	,input: function(id,chain,callback) {
		var e = gms_module_analytics_AnalyticsEvent.INPUT;
		var data = { type : $hxEnums[e.__enum__].__constructs__[e._hx_index], id : id, value : chain};
		return this.send(data,callback);
	}
	,event: function(id,callback) {
		var e = gms_module_analytics_AnalyticsEvent.SCORE;
		var data = { type : $hxEnums[e.__enum__].__constructs__[e._hx_index], id : id, value : "1"};
		return this.send(data,callback);
	}
	,__class__: gms_module_analytics_AnalyticsApi
};
var gms_module_analytics_AnalyticsEvent = $hxEnums["gms.module.analytics.AnalyticsEvent"] = { __ename__ : true, __constructs__ : ["NAVIGATION","SCORE","CHOICE","ACTION","CONTENT","INPUT"]
	,NAVIGATION: {_hx_index:0,__enum__:"gms.module.analytics.AnalyticsEvent",toString:$estr}
	,SCORE: {_hx_index:1,__enum__:"gms.module.analytics.AnalyticsEvent",toString:$estr}
	,CHOICE: {_hx_index:2,__enum__:"gms.module.analytics.AnalyticsEvent",toString:$estr}
	,ACTION: {_hx_index:3,__enum__:"gms.module.analytics.AnalyticsEvent",toString:$estr}
	,CONTENT: {_hx_index:4,__enum__:"gms.module.analytics.AnalyticsEvent",toString:$estr}
	,INPUT: {_hx_index:5,__enum__:"gms.module.analytics.AnalyticsEvent",toString:$estr}
};
var gms_module_analytics_NavigationValue = $hxEnums["gms.module.analytics.NavigationValue"] = { __ename__ : true, __constructs__ : ["LEAVE","ENTER"]
	,LEAVE: {_hx_index:0,__enum__:"gms.module.analytics.NavigationValue",toString:$estr}
	,ENTER: {_hx_index:1,__enum__:"gms.module.analytics.NavigationValue",toString:$estr}
};
var gms_module_analytics_ContentValue = $hxEnums["gms.module.analytics.ContentValue"] = { __ename__ : true, __constructs__ : ["SHOW","HIDE","INTERRUPTED"]
	,SHOW: {_hx_index:0,__enum__:"gms.module.analytics.ContentValue",toString:$estr}
	,HIDE: {_hx_index:1,__enum__:"gms.module.analytics.ContentValue",toString:$estr}
	,INTERRUPTED: {_hx_index:2,__enum__:"gms.module.analytics.ContentValue",toString:$estr}
};
var gms_net_Exception = function(e) {
};
gms_net_Exception.__name__ = true;
gms_net_Exception.prototype = {
	__class__: gms_net_Exception
};
var gms_net_Transporter = function() {
	this.LastConnectTime = -100;
	this.ReconnectStartTime = 0;
	this.ConnectionDesired = false;
	this.ConnectionStatus = false;
	this.Port = 0;
	this.Path = "/";
	this.ConnectionStatus = false;
	this.ConnectionDesired = false;
	this.ReconnectStartTime = 0;
	this.SIG_SocketStatus = new gms_Signal2();
	this.SIG_MessageReceived = new gms_Signal();
	this.SIG_SocketStatus.Add($bind(this,this.OnSocketStatus));
	gms_UpdateManager.Add($bind(this,this.UpdateCB),-1);
};
gms_net_Transporter.__name__ = true;
gms_net_Transporter.prototype = {
	UpdateCB: function(t,dt) {
		if(!this.IsConnected()) {
			if(t - this.LastConnectTime > 3) {
				this.LastConnectTime = t;
				this.Connect();
			}
		}
	}
	,EndpointAddress: function(ip,port) {
		this.IP = ip;
		this.Port = port;
	}
	,SetPath: function(path) {
		this.Path = path;
	}
	,Connect: function() {
		this.ConnectionDesired = true;
		this.ConnectInternal();
	}
	,ConnectInternal: function() {
		throw haxe_Exception.thrown(new gms_net_Exception("Abstract item called"));
	}
	,ReConnect: function() {
		throw haxe_Exception.thrown(new gms_net_Exception("Abstract item called"));
	}
	,Close: function() {
		this.ConnectionDesired = false;
		this.CloseInternal();
	}
	,CloseInternal: function() {
		throw haxe_Exception.thrown(new gms_net_Exception("Abstract item called"));
	}
	,SendText: function(text) {
		if(this.IsConnected()) {
			this.SendTextInternal(text);
		}
	}
	,SendTextInternal: function(text) {
		throw haxe_Exception.thrown(new gms_net_Exception("Abstract item called"));
	}
	,SocketStatus: function() {
		return this.SIG_SocketStatus;
	}
	,MessageReceived: function() {
		return this.SIG_MessageReceived;
	}
	,OnSocketStatus: function(status,error_msg) {
		this.ConnectionStatus = status;
	}
	,ReConnectTimer: function() {
		if(this.ReconnectStartTime > 0) {
			return gms_tool_Timer.stamp() - this.ReconnectStartTime;
		} else {
			return 0;
		}
	}
	,IsConnected: function() {
		return this.ConnectionStatus;
	}
	,__class__: gms_net_Transporter
};
var gms_net_CSTATE = $hxEnums["gms.net.CSTATE"] = { __ename__ : true, __constructs__ : ["DISCONNECTED","CONNECT_INPROGRESS","CONNECTED","DISCONNECT_INPROGRESS"]
	,DISCONNECTED: {_hx_index:0,__enum__:"gms.net.CSTATE",toString:$estr}
	,CONNECT_INPROGRESS: {_hx_index:1,__enum__:"gms.net.CSTATE",toString:$estr}
	,CONNECTED: {_hx_index:2,__enum__:"gms.net.CSTATE",toString:$estr}
	,DISCONNECT_INPROGRESS: {_hx_index:3,__enum__:"gms.net.CSTATE",toString:$estr}
};
var gms_net_TransporterWebSocket = function() {
	gms_net_Transporter.call(this);
	this.ws = null;
	this.ConnectState = gms_net_CSTATE.DISCONNECTED;
	this.DeferSendData = [];
};
gms_net_TransporterWebSocket.__name__ = true;
gms_net_TransporterWebSocket.__super__ = gms_net_Transporter;
gms_net_TransporterWebSocket.prototype = $extend(gms_net_Transporter.prototype,{
	Log: function(txt) {
		if(this.ExternalLog != null) {
			this.ExternalLog(txt);
		}
	}
	,OnMessageReceived: function(msg) {
		this.Log("--> OnMessageReceived : " + msg);
		if(this.ws == null) {
			return;
		}
		if(msg.length > 0) {
			this.SIG_MessageReceived.Send(msg);
		}
	}
	,OnSocketStateChanged: function(state,error_msg) {
		this.SIG_SocketStatus.Send(state,error_msg);
	}
	,CloseInternal: function() {
		if(this.ws == null) {
			return;
		}
		if(this.ConnectState == gms_net_CSTATE.DISCONNECT_INPROGRESS) {
			if(this.ws.get_readyState() == haxe_net_ReadyState.Closed) {
				this.onclose();
			}
			return;
		}
		this.Log("--> close : " + Std.string(this.ConnectState) + " -> " + Std.string(gms_net_CSTATE.DISCONNECT_INPROGRESS));
		this.DeferSendData = [];
		this.ConnectState = gms_net_CSTATE.DISCONNECT_INPROGRESS;
		this.ws.close();
		this.ws.process();
		this.ws = null;
	}
	,ConnectInternal: function() {
		this.Log("--> Try Connecting to server : " + this.IP + ":" + this.Port);
		if(this.ws != null) {
			if(this.ConnectState == gms_net_CSTATE.CONNECT_INPROGRESS) {
				this.Log("Connect in progress, waiting ...");
			} else if(this.ConnectState == gms_net_CSTATE.DISCONNECT_INPROGRESS) {
				this.Log("Close in progress, waiting ...");
			} else {
				this.Log("Already connected : closing connection");
			}
			return;
		}
		this.Log("Connecting ...");
		this.ConnectState = gms_net_CSTATE.CONNECT_INPROGRESS;
		try {
			this.Log("Start create socket : " + this.IP + ":" + this.Port + this.Path);
			this.ws = haxe_net_WebSocket.create(this.IP + ":" + this.Port + this.Path,null,null,true);
		} catch( _g ) {
			var _g1 = haxe_Exception.caught(_g).unwrap();
			if(typeof(_g1) == "string") {
				var msg = _g1;
				this.Log("WebSocket.create failed : " + msg);
			} else {
				throw _g;
			}
		}
		this.AddCallbacks();
		this.ws.process();
	}
	,ReConnect: function() {
		this.Log("<<<<<<<<<<<<<<<< R E C O N N E C T >>>>>>>>>>>>>>>>>>");
		this.ConnectInternal();
	}
	,SendTextInternal: function(data) {
		if(this.ws == null) {
			this.Log("can't send, websocket is null");
			return;
		}
		if(this.ConnectState != gms_net_CSTATE.CONNECTED) {
			this.DeferSendData.push(data);
			return;
		}
		this.Log(">>>>>>>>>>>>>>>>>>");
		this.Log(data);
		this.Log(">>>>>>>>>>>>>>>>>>");
		this.ws.sendString(data);
		this.ws.process();
	}
	,onopen: function() {
		if(this.ws == null) {
			return;
		}
		this.OnSocketStateChanged(true,"CONNECTED");
		this.ConnectState = gms_net_CSTATE.CONNECTED;
		this.Log("<-- Socket connected to server !");
	}
	,onclose: function() {
		if(this.ws == null) {
			return;
		}
		this.Log("<-- Socket closed\n");
		this.RemoveCallbacks();
		this.ws.close();
		this.ws.process();
		this.ws = null;
		this.ConnectState = gms_net_CSTATE.DISCONNECTED;
		this.Log("ON CLOSE");
		this.OnSocketStateChanged(false,"DISCONNECTED");
	}
	,onerror: function(message) {
		this.Log("<-- Error: " + message);
	}
	,AddCallbacks: function() {
		this.ws.onopen = $bind(this,this.onopen);
		this.ws.onclose = $bind(this,this.onclose);
		this.ws.onerror = $bind(this,this.onerror);
		this.ws.onmessageString = $bind(this,this.OnMessageReceived);
	}
	,RemoveCallbacks: function() {
		this.ws.onopen = null;
		this.ws.onclose = null;
		this.ws.onerror = null;
		this.ws.onmessageString = null;
	}
	,__class__: gms_net_TransporterWebSocket
});
var gms_system_Cs2Hx = function() {
};
gms_system_Cs2Hx.__name__ = true;
gms_system_Cs2Hx.NullCheck = function(str) {
	if(str == null) {
		return "";
	} else {
		return str;
	}
};
gms_system_Cs2Hx.IndexOf = function(a,item) {
	var _g = 0;
	var _g1 = a.length;
	while(_g < _g1) {
		var i = _g++;
		if(a[i] == item) {
			return i;
		}
	}
	return -1;
};
gms_system_Cs2Hx.FindIndex = function(a,match) {
	var i = 0;
	var _g = 0;
	while(_g < a.length) {
		var e = a[_g];
		++_g;
		if(match(e)) {
			return i;
		}
		++i;
	}
	return -1;
};
gms_system_Cs2Hx.RemoveAll = function(a,match) {
	var to_remove = [];
	var _g = 0;
	while(_g < a.length) {
		var e = a[_g];
		++_g;
		if(match(e)) {
			to_remove.push(e);
		}
	}
	while(to_remove.length > 0) HxOverrides.remove(a,to_remove.pop());
};
gms_system_Cs2Hx.Clear = function(a) {
	a.splice(0,a.length);
};
gms_system_Cs2Hx.Contains = function(a,item) {
	return gms_system_Cs2Hx.IndexOf(a,item) != -1;
};
gms_system_Cs2Hx.AddRange = function(b,a) {
	var _g = 0;
	while(_g < a.length) {
		var e = a[_g];
		++_g;
		b.push(e);
	}
};
gms_system_Cs2Hx.Equals_String = function(str1,str2) {
	return str1 == str2;
};
gms_system_Cs2Hx.prototype = {
	__class__: gms_system_Cs2Hx
};
var gms_tool_Json = function() {
};
gms_tool_Json.__name__ = true;
gms_tool_Json.stringify = function(obj) {
	return JSON.stringify(obj);
};
gms_tool_Json.parse = function(str,cl) {
	return JSON.parse(str);
};
gms_tool_Json.parse_String = function(str,cl) {
	return JSON.parse(str);
};
gms_tool_Json.prototype = {
	__class__: gms_tool_Json
};
var gms_tool_Timer = function() {
};
gms_tool_Timer.__name__ = true;
gms_tool_Timer.stamp = function() {
	return HxOverrides.now() / 1000 - gms_tool_Timer.StartTime;
};
gms_tool_Timer.prototype = {
	__class__: gms_tool_Timer
};
var gms_tool_Util = function() {
};
gms_tool_Util.__name__ = true;
gms_tool_Util.Find = function(it,match) {
	var _g = 0;
	while(_g < it.length) {
		var i = it[_g];
		++_g;
		if(match(i)) {
			return i;
		}
	}
	return null;
};
gms_tool_Util.prototype = {
	__class__: gms_tool_Util
};
var haxe_Exception = function(message,previous,native) {
	Error.call(this,message);
	this.message = message;
	this.__previousException = previous;
	this.__nativeException = native != null ? native : this;
};
haxe_Exception.__name__ = true;
haxe_Exception.caught = function(value) {
	if(((value) instanceof haxe_Exception)) {
		return value;
	} else if(((value) instanceof Error)) {
		return new haxe_Exception(value.message,null,value);
	} else {
		return new haxe_ValueException(value,null,value);
	}
};
haxe_Exception.thrown = function(value) {
	if(((value) instanceof haxe_Exception)) {
		return value.get_native();
	} else if(((value) instanceof Error)) {
		return value;
	} else {
		var e = new haxe_ValueException(value);
		return e;
	}
};
haxe_Exception.__super__ = Error;
haxe_Exception.prototype = $extend(Error.prototype,{
	unwrap: function() {
		return this.__nativeException;
	}
	,get_native: function() {
		return this.__nativeException;
	}
	,__class__: haxe_Exception
});
var haxe_Timer = function(time_ms) {
	var me = this;
	this.id = setInterval(function() {
		me.run();
	},time_ms);
};
haxe_Timer.__name__ = true;
haxe_Timer.delay = function(f,time_ms) {
	var t = new haxe_Timer(time_ms);
	t.run = function() {
		t.stop();
		f();
	};
	return t;
};
haxe_Timer.prototype = {
	stop: function() {
		if(this.id == null) {
			return;
		}
		clearInterval(this.id);
		this.id = null;
	}
	,run: function() {
	}
	,__class__: haxe_Timer
};
var haxe_ValueException = function(value,previous,native) {
	haxe_Exception.call(this,String(value),previous,native);
	this.value = value;
};
haxe_ValueException.__name__ = true;
haxe_ValueException.__super__ = haxe_Exception;
haxe_ValueException.prototype = $extend(haxe_Exception.prototype,{
	unwrap: function() {
		return this.value;
	}
	,__class__: haxe_ValueException
});
var haxe_crypto_Md5 = function() {
};
haxe_crypto_Md5.__name__ = true;
haxe_crypto_Md5.encode = function(s) {
	var m = new haxe_crypto_Md5();
	var h = m.doEncode(haxe_crypto_Md5.str2blks(s));
	return m.hex(h);
};
haxe_crypto_Md5.str2blks = function(str) {
	var str1 = haxe_io_Bytes.ofString(str);
	var nblk = (str1.length + 8 >> 6) + 1;
	var blks = [];
	var blksSize = nblk * 16;
	var _g = 0;
	var _g1 = blksSize;
	while(_g < _g1) {
		var i = _g++;
		blks[i] = 0;
	}
	var i = 0;
	var max = str1.length;
	var l = max * 8;
	while(i < max) {
		blks[i >> 2] |= str1.b[i] << (l + i) % 4 * 8;
		++i;
	}
	blks[i >> 2] |= 128 << (l + i) % 4 * 8;
	var k = nblk * 16 - 2;
	blks[k] = l & 255;
	blks[k] |= (l >>> 8 & 255) << 8;
	blks[k] |= (l >>> 16 & 255) << 16;
	blks[k] |= (l >>> 24 & 255) << 24;
	return blks;
};
haxe_crypto_Md5.prototype = {
	bitOR: function(a,b) {
		var lsb = a & 1 | b & 1;
		var msb31 = a >>> 1 | b >>> 1;
		return msb31 << 1 | lsb;
	}
	,bitXOR: function(a,b) {
		var lsb = a & 1 ^ b & 1;
		var msb31 = a >>> 1 ^ b >>> 1;
		return msb31 << 1 | lsb;
	}
	,bitAND: function(a,b) {
		var lsb = a & 1 & (b & 1);
		var msb31 = a >>> 1 & b >>> 1;
		return msb31 << 1 | lsb;
	}
	,addme: function(x,y) {
		var lsw = (x & 65535) + (y & 65535);
		var msw = (x >> 16) + (y >> 16) + (lsw >> 16);
		return msw << 16 | lsw & 65535;
	}
	,hex: function(a) {
		var str = "";
		var hex_chr = "0123456789abcdef";
		var _g = 0;
		while(_g < a.length) {
			var num = a[_g];
			++_g;
			str += hex_chr.charAt(num >> 4 & 15) + hex_chr.charAt(num & 15);
			str += hex_chr.charAt(num >> 12 & 15) + hex_chr.charAt(num >> 8 & 15);
			str += hex_chr.charAt(num >> 20 & 15) + hex_chr.charAt(num >> 16 & 15);
			str += hex_chr.charAt(num >> 28 & 15) + hex_chr.charAt(num >> 24 & 15);
		}
		return str;
	}
	,rol: function(num,cnt) {
		return num << cnt | num >>> 32 - cnt;
	}
	,cmn: function(q,a,b,x,s,t) {
		return this.addme(this.rol(this.addme(this.addme(a,q),this.addme(x,t)),s),b);
	}
	,ff: function(a,b,c,d,x,s,t) {
		return this.cmn(this.bitOR(this.bitAND(b,c),this.bitAND(~b,d)),a,b,x,s,t);
	}
	,gg: function(a,b,c,d,x,s,t) {
		return this.cmn(this.bitOR(this.bitAND(b,d),this.bitAND(c,~d)),a,b,x,s,t);
	}
	,hh: function(a,b,c,d,x,s,t) {
		return this.cmn(this.bitXOR(this.bitXOR(b,c),d),a,b,x,s,t);
	}
	,ii: function(a,b,c,d,x,s,t) {
		return this.cmn(this.bitXOR(c,this.bitOR(b,~d)),a,b,x,s,t);
	}
	,doEncode: function(x) {
		var a = 1732584193;
		var b = -271733879;
		var c = -1732584194;
		var d = 271733878;
		var step;
		var i = 0;
		while(i < x.length) {
			var olda = a;
			var oldb = b;
			var oldc = c;
			var oldd = d;
			step = 0;
			a = this.ff(a,b,c,d,x[i],7,-680876936);
			d = this.ff(d,a,b,c,x[i + 1],12,-389564586);
			c = this.ff(c,d,a,b,x[i + 2],17,606105819);
			b = this.ff(b,c,d,a,x[i + 3],22,-1044525330);
			a = this.ff(a,b,c,d,x[i + 4],7,-176418897);
			d = this.ff(d,a,b,c,x[i + 5],12,1200080426);
			c = this.ff(c,d,a,b,x[i + 6],17,-1473231341);
			b = this.ff(b,c,d,a,x[i + 7],22,-45705983);
			a = this.ff(a,b,c,d,x[i + 8],7,1770035416);
			d = this.ff(d,a,b,c,x[i + 9],12,-1958414417);
			c = this.ff(c,d,a,b,x[i + 10],17,-42063);
			b = this.ff(b,c,d,a,x[i + 11],22,-1990404162);
			a = this.ff(a,b,c,d,x[i + 12],7,1804603682);
			d = this.ff(d,a,b,c,x[i + 13],12,-40341101);
			c = this.ff(c,d,a,b,x[i + 14],17,-1502002290);
			b = this.ff(b,c,d,a,x[i + 15],22,1236535329);
			a = this.gg(a,b,c,d,x[i + 1],5,-165796510);
			d = this.gg(d,a,b,c,x[i + 6],9,-1069501632);
			c = this.gg(c,d,a,b,x[i + 11],14,643717713);
			b = this.gg(b,c,d,a,x[i],20,-373897302);
			a = this.gg(a,b,c,d,x[i + 5],5,-701558691);
			d = this.gg(d,a,b,c,x[i + 10],9,38016083);
			c = this.gg(c,d,a,b,x[i + 15],14,-660478335);
			b = this.gg(b,c,d,a,x[i + 4],20,-405537848);
			a = this.gg(a,b,c,d,x[i + 9],5,568446438);
			d = this.gg(d,a,b,c,x[i + 14],9,-1019803690);
			c = this.gg(c,d,a,b,x[i + 3],14,-187363961);
			b = this.gg(b,c,d,a,x[i + 8],20,1163531501);
			a = this.gg(a,b,c,d,x[i + 13],5,-1444681467);
			d = this.gg(d,a,b,c,x[i + 2],9,-51403784);
			c = this.gg(c,d,a,b,x[i + 7],14,1735328473);
			b = this.gg(b,c,d,a,x[i + 12],20,-1926607734);
			a = this.hh(a,b,c,d,x[i + 5],4,-378558);
			d = this.hh(d,a,b,c,x[i + 8],11,-2022574463);
			c = this.hh(c,d,a,b,x[i + 11],16,1839030562);
			b = this.hh(b,c,d,a,x[i + 14],23,-35309556);
			a = this.hh(a,b,c,d,x[i + 1],4,-1530992060);
			d = this.hh(d,a,b,c,x[i + 4],11,1272893353);
			c = this.hh(c,d,a,b,x[i + 7],16,-155497632);
			b = this.hh(b,c,d,a,x[i + 10],23,-1094730640);
			a = this.hh(a,b,c,d,x[i + 13],4,681279174);
			d = this.hh(d,a,b,c,x[i],11,-358537222);
			c = this.hh(c,d,a,b,x[i + 3],16,-722521979);
			b = this.hh(b,c,d,a,x[i + 6],23,76029189);
			a = this.hh(a,b,c,d,x[i + 9],4,-640364487);
			d = this.hh(d,a,b,c,x[i + 12],11,-421815835);
			c = this.hh(c,d,a,b,x[i + 15],16,530742520);
			b = this.hh(b,c,d,a,x[i + 2],23,-995338651);
			a = this.ii(a,b,c,d,x[i],6,-198630844);
			d = this.ii(d,a,b,c,x[i + 7],10,1126891415);
			c = this.ii(c,d,a,b,x[i + 14],15,-1416354905);
			b = this.ii(b,c,d,a,x[i + 5],21,-57434055);
			a = this.ii(a,b,c,d,x[i + 12],6,1700485571);
			d = this.ii(d,a,b,c,x[i + 3],10,-1894986606);
			c = this.ii(c,d,a,b,x[i + 10],15,-1051523);
			b = this.ii(b,c,d,a,x[i + 1],21,-2054922799);
			a = this.ii(a,b,c,d,x[i + 8],6,1873313359);
			d = this.ii(d,a,b,c,x[i + 15],10,-30611744);
			c = this.ii(c,d,a,b,x[i + 6],15,-1560198380);
			b = this.ii(b,c,d,a,x[i + 13],21,1309151649);
			a = this.ii(a,b,c,d,x[i + 4],6,-145523070);
			d = this.ii(d,a,b,c,x[i + 11],10,-1120210379);
			c = this.ii(c,d,a,b,x[i + 2],15,718787259);
			b = this.ii(b,c,d,a,x[i + 9],21,-343485551);
			a = this.addme(a,olda);
			b = this.addme(b,oldb);
			c = this.addme(c,oldc);
			d = this.addme(d,oldd);
			i += 16;
		}
		return [a,b,c,d];
	}
	,__class__: haxe_crypto_Md5
};
var haxe_io_Bytes = function(data) {
	this.length = data.byteLength;
	this.b = new Uint8Array(data);
	this.b.bufferValue = data;
	data.hxBytes = this;
	data.bytes = this.b;
};
haxe_io_Bytes.__name__ = true;
haxe_io_Bytes.ofString = function(s,encoding) {
	if(encoding == haxe_io_Encoding.RawNative) {
		var buf = new Uint8Array(s.length << 1);
		var _g = 0;
		var _g1 = s.length;
		while(_g < _g1) {
			var i = _g++;
			var c = s.charCodeAt(i);
			buf[i << 1] = c & 255;
			buf[i << 1 | 1] = c >> 8;
		}
		return new haxe_io_Bytes(buf.buffer);
	}
	var a = [];
	var i = 0;
	while(i < s.length) {
		var c = s.charCodeAt(i++);
		if(55296 <= c && c <= 56319) {
			c = c - 55232 << 10 | s.charCodeAt(i++) & 1023;
		}
		if(c <= 127) {
			a.push(c);
		} else if(c <= 2047) {
			a.push(192 | c >> 6);
			a.push(128 | c & 63);
		} else if(c <= 65535) {
			a.push(224 | c >> 12);
			a.push(128 | c >> 6 & 63);
			a.push(128 | c & 63);
		} else {
			a.push(240 | c >> 18);
			a.push(128 | c >> 12 & 63);
			a.push(128 | c >> 6 & 63);
			a.push(128 | c & 63);
		}
	}
	return new haxe_io_Bytes(new Uint8Array(a).buffer);
};
haxe_io_Bytes.ofData = function(b) {
	var hb = b.hxBytes;
	if(hb != null) {
		return hb;
	}
	return new haxe_io_Bytes(b);
};
haxe_io_Bytes.prototype = {
	__class__: haxe_io_Bytes
};
var haxe_io_Encoding = $hxEnums["haxe.io.Encoding"] = { __ename__ : true, __constructs__ : ["UTF8","RawNative"]
	,UTF8: {_hx_index:0,__enum__:"haxe.io.Encoding",toString:$estr}
	,RawNative: {_hx_index:1,__enum__:"haxe.io.Encoding",toString:$estr}
};
var haxe_iterators_ArrayIterator = function(array) {
	this.current = 0;
	this.array = array;
};
haxe_iterators_ArrayIterator.__name__ = true;
haxe_iterators_ArrayIterator.prototype = {
	hasNext: function() {
		return this.current < this.array.length;
	}
	,next: function() {
		return this.array[this.current++];
	}
	,__class__: haxe_iterators_ArrayIterator
};
var haxe_net_ReadyState = $hxEnums["haxe.net.ReadyState"] = { __ename__ : true, __constructs__ : ["Connecting","Open","Closing","Closed"]
	,Connecting: {_hx_index:0,__enum__:"haxe.net.ReadyState",toString:$estr}
	,Open: {_hx_index:1,__enum__:"haxe.net.ReadyState",toString:$estr}
	,Closing: {_hx_index:2,__enum__:"haxe.net.ReadyState",toString:$estr}
	,Closed: {_hx_index:3,__enum__:"haxe.net.ReadyState",toString:$estr}
};
var haxe_net_WebSocket = function() {
};
haxe_net_WebSocket.__name__ = true;
haxe_net_WebSocket.create = function(url,protocols,origin,debug) {
	if(debug == null) {
		debug = false;
	}
	return new haxe_net_impl_WebSocketJs(url,protocols);
};
haxe_net_WebSocket.defer = function(callback) {
	haxe_Timer.delay(callback,0);
};
haxe_net_WebSocket.prototype = {
	process: function() {
	}
	,sendString: function(message) {
	}
	,sendBytes: function(message) {
	}
	,close: function() {
	}
	,get_readyState: function() {
		throw haxe_Exception.thrown("Not implemented");
	}
	,onopen: function() {
	}
	,onerror: function(message) {
	}
	,onmessageString: function(message) {
	}
	,onmessageBytes: function(message) {
	}
	,onclose: function() {
	}
	,__class__: haxe_net_WebSocket
};
var haxe_net_impl_BytesRW = function() {
	this.chunks = [];
	this.currentData = null;
	this.currentOffset = 0;
	this.available = 0;
};
haxe_net_impl_BytesRW.__name__ = true;
haxe_net_impl_BytesRW.prototype = {
	writeByte: function(v) {
		var b = new haxe_io_Bytes(new ArrayBuffer(1));
		b.b[0] = v;
		this.writeBytes(b);
	}
	,writeShort: function(v) {
		var b = new haxe_io_Bytes(new ArrayBuffer(2));
		b.b[0] = v >> 8 & 255;
		b.b[1] = v & 255;
		this.writeBytes(b);
	}
	,writeInt: function(v) {
		var b = new haxe_io_Bytes(new ArrayBuffer(4));
		b.b[0] = v >> 24 & 255;
		b.b[1] = v >> 16 & 255;
		b.b[2] = v >> 8 & 255;
		b.b[3] = v & 255;
		this.writeBytes(b);
	}
	,writeBytes: function(data) {
		this.chunks.push(data);
		this.available += data.length;
	}
	,readAllAvailableBytes: function() {
		return this.readBytes(this.available);
	}
	,readBytes: function(count) {
		var count2 = Math.min(count,this.available) | 0;
		var out = new haxe_io_Bytes(new ArrayBuffer(count2));
		var _g = 0;
		var _g1 = count2;
		while(_g < _g1) {
			var n = _g++;
			var v = this.readByte();
			out.b[n] = v;
		}
		return out;
	}
	,readUnsignedShort: function() {
		var h = this.readByte();
		var l = this.readByte();
		return h << 8 | l;
	}
	,readUnsignedInt: function() {
		var v3 = this.readByte();
		var v2 = this.readByte();
		var v1 = this.readByte();
		var v0 = this.readByte();
		return v3 << 24 | v2 << 16 | v1 << 8 | v0;
	}
	,readByte: function() {
		if(this.available <= 0) {
			throw haxe_Exception.thrown("Not bytes available");
		}
		while(this.currentData == null || this.currentOffset >= this.currentData.length) {
			this.currentOffset = 0;
			this.currentData = this.chunks.shift();
		}
		this.available--;
		return this.currentData.b[this.currentOffset++];
	}
	,__class__: haxe_net_impl_BytesRW
};
var haxe_net_impl_WebSocketJs = function(url,protocols) {
	var _gthis = this;
	haxe_net_WebSocket.call(this);
	if(protocols != null) {
		this.impl = new WebSocket(url,protocols);
	} else {
		this.impl = new WebSocket(url);
	}
	this.impl.onopen = function(e) {
		_gthis.onopen();
	};
	this.impl.onclose = function(e) {
		_gthis.onclose();
	};
	this.impl.onerror = function(e) {
		_gthis.onerror("error");
	};
	this.impl.onmessage = function(e) {
		var m = e.data;
		if(typeof(m) == "string") {
			_gthis.onmessageString(m);
		} else if(((m) instanceof ArrayBuffer)) {
			console.log("haxe/net/impl/WebSocketJs.hx:33:","Unhandled websocket onmessage " + m);
		} else if(((m) instanceof Blob)) {
			var arrayBuffer;
			var fileReader = new FileReader();
			fileReader.onload = function() {
				arrayBuffer = fileReader.result;
				_gthis.onmessageBytes(haxe_io_Bytes.ofData(arrayBuffer));
			};
			fileReader.readAsArrayBuffer(js_Boot.__cast(m , Blob));
		} else {
			console.log("haxe/net/impl/WebSocketJs.hx:44:","Unhandled websocket onmessage " + m);
		}
	};
};
haxe_net_impl_WebSocketJs.__name__ = true;
haxe_net_impl_WebSocketJs.__super__ = haxe_net_WebSocket;
haxe_net_impl_WebSocketJs.prototype = $extend(haxe_net_WebSocket.prototype,{
	sendString: function(message) {
		this.impl.send(message);
	}
	,sendBytes: function(message) {
		this.impl.send(message.b.bufferValue);
	}
	,close: function() {
		this.impl.close();
	}
	,get_readyState: function() {
		switch(this.impl.readyState) {
		case 0:
			return haxe_net_ReadyState.Connecting;
		case 1:
			return haxe_net_ReadyState.Open;
		case 2:
			return haxe_net_ReadyState.Closing;
		case 3:
			return haxe_net_ReadyState.Closed;
		default:
			throw haxe_Exception.thrown("Unexpected websocket state");
		}
	}
	,__class__: haxe_net_impl_WebSocketJs
});
var js_Boot = function() { };
js_Boot.__name__ = true;
js_Boot.getClass = function(o) {
	if(o == null) {
		return null;
	} else if(((o) instanceof Array)) {
		return Array;
	} else {
		var cl = o.__class__;
		if(cl != null) {
			return cl;
		}
		var name = js_Boot.__nativeClassName(o);
		if(name != null) {
			return js_Boot.__resolveNativeClass(name);
		}
		return null;
	}
};
js_Boot.__string_rec = function(o,s) {
	if(o == null) {
		return "null";
	}
	if(s.length >= 5) {
		return "<...>";
	}
	var t = typeof(o);
	if(t == "function" && (o.__name__ || o.__ename__)) {
		t = "object";
	}
	switch(t) {
	case "function":
		return "<function>";
	case "object":
		if(o.__enum__) {
			var e = $hxEnums[o.__enum__];
			var n = e.__constructs__[o._hx_index];
			var con = e[n];
			if(con.__params__) {
				s = s + "\t";
				return n + "(" + ((function($this) {
					var $r;
					var _g = [];
					{
						var _g1 = 0;
						var _g2 = con.__params__;
						while(true) {
							if(!(_g1 < _g2.length)) {
								break;
							}
							var p = _g2[_g1];
							_g1 = _g1 + 1;
							_g.push(js_Boot.__string_rec(o[p],s));
						}
					}
					$r = _g;
					return $r;
				}(this))).join(",") + ")";
			} else {
				return n;
			}
		}
		if(((o) instanceof Array)) {
			var str = "[";
			s += "\t";
			var _g = 0;
			var _g1 = o.length;
			while(_g < _g1) {
				var i = _g++;
				str += (i > 0 ? "," : "") + js_Boot.__string_rec(o[i],s);
			}
			str += "]";
			return str;
		}
		var tostr;
		try {
			tostr = o.toString;
		} catch( _g ) {
			return "???";
		}
		if(tostr != null && tostr != Object.toString && typeof(tostr) == "function") {
			var s2 = o.toString();
			if(s2 != "[object Object]") {
				return s2;
			}
		}
		var str = "{\n";
		s += "\t";
		var hasp = o.hasOwnProperty != null;
		var k = null;
		for( k in o ) {
		if(hasp && !o.hasOwnProperty(k)) {
			continue;
		}
		if(k == "prototype" || k == "__class__" || k == "__super__" || k == "__interfaces__" || k == "__properties__") {
			continue;
		}
		if(str.length != 2) {
			str += ", \n";
		}
		str += s + k + " : " + js_Boot.__string_rec(o[k],s);
		}
		s = s.substring(1);
		str += "\n" + s + "}";
		return str;
	case "string":
		return o;
	default:
		return String(o);
	}
};
js_Boot.__interfLoop = function(cc,cl) {
	if(cc == null) {
		return false;
	}
	if(cc == cl) {
		return true;
	}
	var intf = cc.__interfaces__;
	if(intf != null) {
		var _g = 0;
		var _g1 = intf.length;
		while(_g < _g1) {
			var i = _g++;
			var i1 = intf[i];
			if(i1 == cl || js_Boot.__interfLoop(i1,cl)) {
				return true;
			}
		}
	}
	return js_Boot.__interfLoop(cc.__super__,cl);
};
js_Boot.__instanceof = function(o,cl) {
	if(cl == null) {
		return false;
	}
	switch(cl) {
	case Array:
		return ((o) instanceof Array);
	case Bool:
		return typeof(o) == "boolean";
	case Dynamic:
		return o != null;
	case Float:
		return typeof(o) == "number";
	case Int:
		if(typeof(o) == "number") {
			return ((o | 0) === o);
		} else {
			return false;
		}
		break;
	case String:
		return typeof(o) == "string";
	default:
		if(o != null) {
			if(typeof(cl) == "function") {
				if(js_Boot.__downcastCheck(o,cl)) {
					return true;
				}
			} else if(typeof(cl) == "object" && js_Boot.__isNativeObj(cl)) {
				if(((o) instanceof cl)) {
					return true;
				}
			}
		} else {
			return false;
		}
		if(cl == Class ? o.__name__ != null : false) {
			return true;
		}
		if(cl == Enum ? o.__ename__ != null : false) {
			return true;
		}
		return o.__enum__ != null ? $hxEnums[o.__enum__] == cl : false;
	}
};
js_Boot.__downcastCheck = function(o,cl) {
	if(!((o) instanceof cl)) {
		if(cl.__isInterface__) {
			return js_Boot.__interfLoop(js_Boot.getClass(o),cl);
		} else {
			return false;
		}
	} else {
		return true;
	}
};
js_Boot.__cast = function(o,t) {
	if(o == null || js_Boot.__instanceof(o,t)) {
		return o;
	} else {
		throw haxe_Exception.thrown("Cannot cast " + Std.string(o) + " to " + Std.string(t));
	}
};
js_Boot.__nativeClassName = function(o) {
	var name = js_Boot.__toStr.call(o).slice(8,-1);
	if(name == "Object" || name == "Function" || name == "Math" || name == "JSON") {
		return null;
	}
	return name;
};
js_Boot.__isNativeObj = function(o) {
	return js_Boot.__nativeClassName(o) != null;
};
js_Boot.__resolveNativeClass = function(name) {
	return $global[name];
};
function $bind(o,m) { if( m == null ) return null; if( m.__id__ == null ) m.__id__ = $global.$haxeUID++; var f; if( o.hx__closures__ == null ) o.hx__closures__ = {}; else f = o.hx__closures__[m.__id__]; if( f == null ) { f = m.bind(o); o.hx__closures__[m.__id__] = f; } return f; }
$global.$haxeUID |= 0;
if(typeof(performance) != "undefined" ? typeof(performance.now) == "function" : false) {
	HxOverrides.now = performance.now.bind(performance);
}
String.prototype.__class__ = String;
String.__name__ = true;
Array.__name__ = true;
var Int = { };
var Dynamic = { };
var Float = Number;
var Bool = Boolean;
var Class = { };
var Enum = { };
js_Boot.__toStr = ({ }).toString;
gms_UpdateManager.PrevTime = 0;
gms_UpdateManager.MinimalTimeStep = 0;
gms_VertxCmd.Type_ClientCmd = "ClientCmd";
gms_VertxCmd.Type_ClientCmdResult = "ClientCmdResult";
gms_VertxCmd.Type_ClientCmdResultSlice = "ClientCmdResultSlice";
gms_VertxCmd.Type_ServerCmd = "ServerCmd";
gms_VertxCmd_$MessageSlot.Block_TimeMax = 5;
gms_VertxCmd_$MessageSlot.Reply_TimeMax = 10;
gms_module_analytics_AnalyticsApi.global = new gms_module_analytics_AnalyticsApi();
gms_tool_Timer.StartTime = 0;
})(typeof exports != "undefined" ? exports : typeof window != "undefined" ? window : typeof self != "undefined" ? self : this, typeof window != "undefined" ? window : typeof global != "undefined" ? global : typeof self != "undefined" ? self : this);
